# Generated by Django 3.2.5 on 2021-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_path',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='static/media/images/187.png', upload_to='images'),
        ),
    ]
