# Generated by Django 3.2.5 on 2021-10-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20211015_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_path',
            field=models.CharField(default='static/images/187.jpg', max_length=200),
        ),
    ]
