# Generated by Django 3.2.5 on 2021-10-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_alter_images_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_path',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='media/images/187.jpg', upload_to='images'),
        ),
    ]
