# Generated by Django 3.2.5 on 2021-10-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_auto_20211022_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6),
        ),
        migrations.AddField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(blank=True, help_text='required score in %', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(blank=True, help_text='duration of the quiz in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='cell_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='component',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='microscopy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='organism',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
