# Generated by Django 3.2.5 on 2021-11-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created',
        ),
    ]
